---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-hello-world-
  namespace: freighter
spec:
  pipelineRef:
    name: buildah-pipeline
  serviceAccountName: build-bot
  params:
    - name: image-name
      value: lawsford/tekton-registry:0.1
    - name: github-repo-url
      value: https://github.com/lawsford/cron-pipelines
    - name: github-repo-revision
      value: master
    - name: dockerfile-path
      value: images/example/Dockerfile
    - name: docker-context
      value: images/example
  workspaces:
    - name: source
      subPath: source
      persistentVolumeClaim:
        claimName: cache-image-ws-pvc
